### ISSUE TITLE
Remove AppHeader Warning

### ISSUE THREAD

**Issue by djirdehh** [clshu/tinyhouse#1]
👋 Hi Chin-Long Shu!

Appreciate you linking this repo for me to dive in and reproduce the issue. I've noticed the issue you're seeing with `AppHeader` actually comes from Ant Design's `Affix` component in the main `src/index.tsx` file. It appears that wrapping `Affix` directly over `AppHeader` causes the console warning. To avoid the warning, you can wrap the `<AppHeader />` component with a `<div></div>`.

Before in `client/src/index.tsx`:
```
return (
  <Router>
    <Affix offsetTop={0} className="app__affix-header">
      <AppHeader viewer={viewer} setViewer={setViewer} />
    </Affix>

    // ...
  </Router>
)
```

After in `client/src/index.tsx`:

```
return (
  <Router>
    <Affix offsetTop={0} className="app__affix-header">
      <div>
        <AppHeader viewer={viewer} setViewer={setViewer} />
      </div>
    </Affix>

    // ...
  </Router>
)
```

**Comment by clshu** [comment]
Hi Hassan,
Thanks for taking time to reply. I supposed this is a glitch caused by
newer version of antd.

Chin-Long Shu
